package ubc.cosc322.util;

import org.junit.jupiter.api.Test;

import it.unimi.dsi.fastutil.ints.IntArrayList;
import ubc.cosc322.eval.MinDist;
import ubc.cosc322.eval.HeuristicMethod;

import static org.junit.jupiter.api.Assertions.*;

public class MoveTest {
	private static final byte WHITE = 0;
	private static final byte BLACK = 1;

	@Test
	public void testEncoding() {
		byte start = 24;
		byte end = 54;
		byte arrow = 13;
		byte player = 0;

		int move = Move.encode(start, end, arrow, player);

		assertEquals(start, Move.start(move));
		assertEquals(end, Move.start(end));
		assertEquals(arrow, Move.start(arrow));
		assertEquals(player, Move.player(move));
	}

	@Test
	public void testGetAllMoves() {
		long[] allEmpty = BitBoard.create();
		allEmpty[0] = Long.MAX_VALUE;
		allEmpty[1] = Long.MAX_VALUE;
		byte player = 1;

		for (byte i = 0; i < 99; i++) {
			BitBoard.unflag(allEmpty, i);
			IntArrayList moves = Move.getAll(allEmpty, i, player);
			for (int move : moves) {
				assertEquals(Move.start(move), i);
			}

			// at least one of the moves should end with the queen firing an
			// arrow back to her original position. This check ensures that the
			// determination of possible arrow moves accounts for the fact that
			// the queen is no longer occupying her original position.
			boolean oneHitStart = false;
			for (int move : moves) {
				if (Move.arrow(move) == i) {
					oneHitStart = true;
				}
			}
			assertTrue(oneHitStart);
			BitBoard.flag(allEmpty, i);
		}
	}

	@Test 
	public void testApplyMoves() {
		// start with a fully empty board.
		final long[] empty = BitBoard.create();
		empty[0] = Long.MAX_VALUE;
		empty[1] = Long.MAX_VALUE;

		// set a queen in a random spot.
		final byte queenInitial = (byte) (Math.random() * 100);
		BitBoard.unflag(empty, queenInitial);
		final byte player = 0;
		final byte[] white = new byte[4];
		final byte[] black = new byte[4];
		white[0] = queenInitial;

		// let the queen move randomly until she no longer can.
		IntArrayList availableMoves = Move.getAll(empty, queenInitial, player);
		while (!availableMoves.isEmpty()) {
			int randomIndex = (int) (Math.random() * availableMoves.size());
			int move = availableMoves.getInt(randomIndex);

			Move.apply(empty, white, black, move);

			// unless the queen fired her arrow back to her starting position,
			// the starting position should be empty.
			if (Move.arrow(move) != Move.start(move)) {
				assertTrue(BitBoard.flagged(empty, Move.start(move)));
			}
			// the arrow position is not empty.
			assertFalse(BitBoard.flagged(empty, Move.arrow(move)));
			// the new position is not empty.
			assertFalse(BitBoard.flagged(empty, Move.end(move)));

			availableMoves = Move.getAll(empty, Move.end(move), player);
		}
	}

	@Test
	public void testEvalSequence() {
		// set up the opening board state. We want a realistic board so that
		// the evaluation function doesn't have any unexpected behavior.
		final long[] empty = BitBoard.create();
		for (byte i = 0; i < 100; i++) BitBoard.flag(empty, i);

		final byte[] white = { 60, 93, 96, 69 };
		final byte[] black = { 30, 03, 06, 39 };
		for (byte queen : white) BitBoard.unflag(empty, queen);
		for (byte queen : black) BitBoard.unflag(empty, queen);

		/*
		 	   0 1 2 3 4 5 6 7 8 9
		 	0  _ _ _ B _ _ B _ _ _  Legend
		 	1  _ _ _ _ _ _ _ _ _ _  -----------------------
		 	2  _ _ _ _ _ _ _ _ _ _  _: empty square
		 	3  B _ _ _ _ _ _ _ _ B  X: arrow-struck square
		 	4  _ _ _ _ _ _ _ _ _ _  W: white queen
		 	5  _ _ _ _ _ _ _ _ _ _  B: black queen
		 	6  W _ _ _ _ _ _ _ _ W
		 	7  _ _ _ _ _ _ _ _ _ _
		 	8  _ _ _ _ _ _ _ _ _ _
		 	9  _ _ _ W _ _ W _ _ _
		 
		 		Starting Board
		 
		  (this was generated by running Display.board(...))

		 */

		// Next, we generate a sequence of 20 random moves and apply them to a 
		// copy of our board.
		final long[] emptyCpy = BitBoard.copy(empty);
		final byte[] whiteCpy =  { 60, 93, 96, 69 };
		final byte[] blackCpy = { 30, 03, 06, 39 };
		
		final IntArrayList sequence = new IntArrayList(20);
		byte activePlayer = WHITE;

		for (int i = 0; i < sequence.size(); i++) {
			IntArrayList possibleMoves = Move.getAll(
				emptyCpy, 
				activePlayer == WHITE ? whiteCpy : blackCpy, 
				activePlayer
			);
			int randomMove = possibleMoves.getInt(
				(int) (Math.random() * possibleMoves.size())
			);

			sequence.addLast(randomMove);
			Move.apply(emptyCpy, whiteCpy, blackCpy, randomMove);

			activePlayer = activePlayer == WHITE ? BLACK : WHITE;
		}

		// Finally, we evaluate the board and then compare its result to the
		// `evaluateSequence` result. They should be identical, if everything
		// works as intended.

		final HeuristicMethod heuristic = new MinDist();

		heuristic.setBoard(emptyCpy, whiteCpy, blackCpy);
		double evalCpy = heuristic.evaluate(WHITE);

		double eval = Move.evaluateSequence(
			empty, white, black, sequence, heuristic, WHITE
		);

		assertEquals(eval, evalCpy);
	}
}
