/*
Copyright © 2026 Chad Glazier <chadglazier@outlook.com>
*/
package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/Chad-Glazier/game-of-the-amazons-ai/scripts/bitboard"
	"github.com/spf13/cobra"
)

// bitboardsCmd represents the moves command
var bitboardsCmd = &cobra.Command{
	Use:   "bitboards <output_dir>",
	Short: "Generates the bitboards for efficient Amazons calculations",
	Args: cobra.MinimumNArgs(1),
	Long: `Generates a file in the specified directory named "P.java" (for
"precomputed") which has hard-coded Java matrices storing 
bitboards useful in various amazons movement/distance 
calculations.`,
	Run: func(cmd *cobra.Command, args []string) {
		outputDir := args[0];

		_, err := os.Stat(outputDir)
		if os.IsNotExist(err) {
			fmt.Printf(
				"Specified output directory \"%s\" does not exist.", 
				outputDir,
			)
			return
		}
		if err != nil {
			panic(err)
		}

		outputPath := filepath.Join(outputDir, "P.java")
		w, err := os.OpenFile(
			outputPath, 
			os.O_CREATE | os.O_WRONLY | os.O_TRUNC, 
			0644,
		)
		if err != nil {
			panic(err)
		}
		defer w.Close()

		writeMoves(w)
	},
}

func init() {
	rootCmd.AddCommand(bitboardsCmd)
}

func writeMoves(w io.Writer) {
	w.Write([]byte (header))
	defer w.Write([]byte (footer))

	writeRayBoards(w)
	writeInclusiveRayBoards(w)
	writeSquareBoards(w)
	
	// Currently, there are too many in-between boards to fit in the JVM's
	// hard-set limit for static methods. To use these boards, we need to put
	// them into an encoded binary file and then load them explicitly in the
	// Java class.
	// TODO: Maybe create a static method for the Java class, "initialize," 
	// which does this.
	// writeInBetweenBoards(w)
}

var header = `//
// This is a generated file. See "scripts/README.md" for more information.
//
package ubc.cosc322.bitboard;

/**
 * This class stores precomputed (abbreviated to "P" for convenience) 
 * bitboards. 
 *
 * The bitboards were generated by the script in "scripts/", see the README
 * in that directory for more information.
 */
public class P {
	/** Represents the "West" direction; i.e., lesser column indices. */
	public static final byte W = 0;
	/** Represents the "Northwest" direction. */
	public static final byte NW = 1;
	/** Represents the "North" direction; i.e., lesser row indices. */
	public static final byte N = 2;
	/** Represents the "Northeast" direction. */ 
	public static final byte NE = 3;
	/** Represents the "East" direction; i.e., greater column indices. */
	public static final byte E = 4;
	/** Represents the "Southeast" direction. */
	public static final byte SE = 5;
	/** Represnts the "South" direction; i.e., greater row indices. */
	public static final byte S = 6;
	/** Represents the "Southwest" direction. */
	public static final byte SW = 7;


`
var footer = `
}
`


func writeRayBoards(w io.Writer) {
	w.Write([]byte(`
	/**
	 * A matrix that stores the bitboards that represent rays a queen can
	 * move along based on (1) the starting position index and (2) the 
	 * direction of the move. E.g., to get the move bitboard for a queen at 
	 * position 32 moving North, you would access:
	 *
	 * <pre>{@code
	 * long[] ray = P.ray[32][P.N];
	 * }</pre>
	 */
	public static final long[][][] ray = {` + "\n"))

	for row := range 10 {
		for col := range 10 {
			fmt.Fprintf(w, "\t\t{\n")
			for dir := range 8 {
				fmt.Fprintf(w, "\t\t\t")
				bitboard.Write(w, bitboard.Ray(row, col, dir))
				fmt.Fprintf(w, ",\n")
			}
			fmt.Fprintf(w, "\t\t},\n")
		}
	}

	fmt.Fprintf(w, "\t};\n")
}

func writeSquareBoards(w io.Writer) {
	w.Write([]byte(`
	/**
	 * Stores bitboards that have only a single square flagged; the indexed
	 * position. E.g., if you want a bitboard with only a single flag at the
	 * position index 12, you would use
	 *
	 * <pre>{@code
	 * long[] square = P.square[12];
	 * }</pre>
	 */
	public static final long[][] square = {` + "\n"))

	for row := range 10 {
		for col := range 10 {
			fmt.Fprintf(w, "\t\t")
			bitboard.Write(w, bitboard.Square(row, col))
			fmt.Fprintf(w, ",\n")
		}
	}

	fmt.Fprintf(w, "\t};\n")
}

func writeInclusiveRayBoards(w io.Writer) {
	w.Write([]byte(`
	/**
	 * A matrix that stores the bitboards that represent rays a queen can
	 * move along based on (1) the starting position index and (2) the 
	 * direction of the move. E.g., to get the move bitboard for a queen at 
	 * position 32 moving North, you would access:
	 *
	 * <pre>{@code
	 * long[] ray = P.ray[32][P.N];
	 * }</pre>
	 * 
	 * This matrix is distinct from {@link #ray} because this one includes the
	 * given position as part of the ray. You shouldn't typically use this for
	 * queen movements, but it may be useful in calculating the ray segment
	 * that should be removed due to a blocker.
	 *
	 * Note: The index P.ray[100] is defined for all directions, but only holds
	 * empty boards.
	 */
	public static final long[][][] inclusiveRay = {` + "\n"))

	for row := range 10 {
		for col := range 10 {
			fmt.Fprintf(w, "\t\t{\n")
			for dir := range 8 {
				fmt.Fprintf(w, "\t\t\t")
				bitboard.Write(w, bitboard.InclusiveRay(row, col, dir))
				fmt.Fprintf(w, ",\n")
			}
			fmt.Fprintf(w, "\t\t},\n")
		}
	}
		
	fmt.Fprintf(w, "\t\t{\n")
	for range 8 {
		fmt.Fprintf(w, "\t\t\t")
		bitboard.Write(w, bitboard.BitBoard{})
		fmt.Fprintf(w, ",\n")
	}
	fmt.Fprintf(w, "\t\t},\n")
	
	fmt.Fprintf(w, "\t};\n")
}

func writeInBetweenBoards(w io.Writer) {
	w.Write([]byte(`
	/**
	 * A matrix that stores the bitboards that represent ray segments between
	 * two given positions (exclusive). E.g, if you have a queen at position
	 * 11 and a blocker at 14, the available squares the queen could move to
	 * between her starting position and the blocker would be given by:
	 *
	 * <pre>{@code
	 * long[] positions = P.between[11][14];
	 * }</pre>
	 */
	public static final long[][][] between = {` + "\n"))

	for arow := range 10 {
		for acol := range 10 {
			fmt.Fprintf(w, "\t\t{\n")
			for brow := range 10 {
				for bcol := range 10 {
					fmt.Fprintf(w, "\t\t\t")
					bitboard.Write(w, bitboard.SegmentBetween(
						arow, acol, brow, bcol,
					))
					fmt.Fprintf(w, ",\n")
				}
			}
			fmt.Fprintf(w, "\t\t},\n")
		}
	}

	fmt.Fprintf(w, "\t};\n")
}